title: Benjamin GILBERT
url: "https://bglbrt.github.io"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "About"
    link: "/"
    lang: "en"
  - name: "Research"
    link: "research"
    lang: "en"
  - name: "Teaching"
    link: "teaching"
    lang: "en"
  - name: "Resume"
    link: "resume.pdf"
    lang: "en"
  - name: "Contact"
    link: "contact"
    lang: "en"
  - name: "À propos"
    link: "/"
    lang: "fr"
  - name: "Recherche"
    link: "recherche"
    lang: "fr"
  - name: "Enseignement"
    link: "enseignement"
    lang: "fr"
  - name: "CV"
    link: "CV.pdf"
    lang: "fr"
  - name: "Contact"
    link: "contact"
    lang: "fr"