title: Benjamin GILBERT
url: "https://bglbrt.github.io"
baseurl: ""

markdown: kramdown

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"