title: Benjamin GILBERT
url: "https://bglbrt.github.io"
baseurl: ""

markdown: kramdown

languages: ["fr", "en"]
default_lang: "fr"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Research"
   link: "research"
 - name: "Teaching"
   link: "teaching"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"